spring.application.name=coffee-cupping-api

# Load local developer settings if the file exists
spring.config.import=optional:classpath:application-local.properties

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/coffee_cupping_db

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Server
server.port=8080

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
